name: Deploy model to Vertex AI
on:
  push:
    branches:
      - dhananjay_model
  pull_request:
    branches:
      - dhananjay_model
  workflow_dispatch:
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCS_BUCKET: "nih-dataset-mlops"

jobs:
  deploy-to-vertex-ai:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Google Cloud Authentication
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Organize and Upload Model to GCS
    - name: Organize and Upload Model to GCS
      run: |
        echo "Starting GCS operations..."
          
        # Define paths
        GCS_LATEST_PATH="gs://nih-dataset-mlops/Dummy/Latest"
        GCS_VERSIONED_PATH="gs://nih-dataset-mlops/Dummy/Versioned"

        # List files in the Latest folder
        echo "Listing files in the Latest folder:"
        gsutil ls "$GCS_LATEST_PATH/"

        # Move all files from 'Latest' to 'Versioned' with their name + timestamp
        echo "Moving files from Latest to Versioned..."
        for file in $(gsutil ls "$GCS_LATEST_PATH/"); do
          # Get file's actual timestamp from metadata
          FILE_TIMESTAMP=$(gsutil stat "$file" | grep "Update time:" | awk '{print $3"-"$4}' | sed 's/[:-]//g' | sed 's/\..*//')
          BASENAME=$(basename "$file")

          # Print file details before moving
          echo "Processing file: $BASENAME with timestamp: $FILE_TIMESTAMP"

          # Move the file to the 'Versioned' folder with the actual timestamp in its name
          gsutil mv "$file" "$GCS_VERSIONED_PATH/${BASENAME}_${FILE_TIMESTAMP}"
        done

        # Upload a text file from the repository to the 'Latest' folder
        echo "Uploading text file from repository to the Latest folder..."
        gsutil cp "model/Filedummy3.txt" "$GCS_LATEST_PATH/Filedummy3.txt"
        echo "GCS operations completed successfully."

    - name: Notify on Success
      if: success()
      run: |
          echo "✅ Files successfully moved and uploaded to GCS."

    - name: Notify on Failure
      if: failure()
      run: |
          echo "❌ GCS operations failed."
