name: Deploy model to Vertex AI
on:
  push:
    branches:
      - dhanush_model
  pull_request:
    branches:
      - dhanush_model
  workflow_dispatch:
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  IMAGE_NAME: "ml-model-image"
  REGISTRY: "us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ml-models-new"
  GCS_BUCKET: "nih-dataset-mlops"

jobs:
  deploy-to-vertex-ai:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    #Google Cloud Authentication
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'      

    # Step 4: Create a model in Vertex AI Model Registry
    - name: Create or check for Existing Model Registry in Vertex AI
      id: create-model
      run: |
        MODEL_NAME="gitmodel"
        REGION="us-east1"
        MODEL_URI="gs://nih-dataset-mlops/Testing"
        echo "Checking if model exists in Vertex AI Model Registry..."
        MODEL_ID=$(gcloud ai models list --region=$REGION --filter="display_name='gitmodel'" --format="value(name)")

        if [ -z "$MODEL_ID" ]; then
          echo "Model does not exist. Creating a new model..."
          gcloud ai models upload \
            --region=$REGION \
            --display-name=$MODEL_NAME \
            --artifact-uri=$MODEL_URI \
            --container-image-uri=us-docker.pkg.dev/vertex-ai/prediction/pytorch-cpu.2-1:latest
          MODEL_ID=$(gcloud ai models list --region=$REGION --filter="display_name='gitmodel'" --format="value(name)")
        else
          echo "Model already exists: $MODEL_ID"
        fi
        echo "MODEL_ID=$MODEL_ID"
        echo "MODEL_ID=$MODEL_ID" >> $GITHUB_ENV
          
      # Step 7: Create or Reuse an Endpoint
    - name: Create or Reuse Endpoint
      id: create_endpoint
      run: |
          echo "Checking for existing endpoint..."
          REGION="us-east1"
          ENDPOINT_NAME=$(gcloud ai endpoints list --region=$REGION --filter="display_name='gitmodelendpoint'" --format="value(name)")

          if [ -z "$ENDPOINT_NAME" ]; then
            echo "No existing endpoint found. Creating a new one..."
            ENDPOINT_NAME=$(gcloud ai endpoints create --region=$REGION --display-name=gitmodelendpoint --format="value(name)")
          fi

          if [ -z "$ENDPOINT_NAME" ]; then
            echo "ERROR: Failed to create or retrieve endpoint. Exiting workflow."
            exit 1
          fi

          echo "ENDPOINT_NAME=$ENDPOINT_NAME" 
          echo "Retrieved or created ENDPOINT_NAME: $ENDPOINT_NAME"
          echo "ENDPOINT_NAME=$ENDPOINT_NAME" >> $GITHUB_ENV


      # Step 8: Deploy Model to Endpoint 
    - name: Deploy Model to Endpoint
      run: |
          echo "Deploying model $MODEL_ID to endpoint $ENDPOINT_NAME..."
          gcloud ai endpoints deploy-model $ENDPOINT_NAME --region=us-east1 --model=$MODEL_ID --display-name=gitmodelendpoint-deployment --machine-type=n1-standard-2 --traffic-split=0=100   


    # Step 9: Get Endpoint URI
    - name: Get Endpoint URI
      run: |
        GCP_PROJECT_ID='812555529114'
        REGION="us-east1"
        ENDPOINT=$(gcloud ai endpoints list --region us-east1 --filter="displayName='gitmodelendpoint'" --format="value(name)")
        echo "Endpoint URI: https://us-east1-aiplatform.googleapis.com/v1/projects/${GCP_PROJECT_ID}/locations/${REGION}/endpoints/$ENDPOINT_NAME:predict"
      
    # Step 10: Streamlit Application Deployment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Deploy/Run Streamlit App
      run: |
        streamlit run deploy_streamlit.py
      env:
        PORT: 8501
