name: Deploy Model to Vertex AI

on:
  push:
    branches:
      - dhanush_model  # Replace 'main' with your branch name if needed

jobs:
  deploy-to-vertex-ai:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: black-resource-440218-c3

    # Step 3: Authenticate and configure gcloud
    - name: Authenticate to Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
        gcloud config set project black-resource-440218-c3

    # Step 4: Create a model in Vertex AI Model Registry
    - name: Create Model Registry in Vertex AI
      id: create-model
      run: |
        MODEL_NAME="gitdeploy"
        REGION="us-east1"
        MODEL_URI="gs://nih-dataset-mlops/Testing/model.mar"

        gcloud ai models upload \
          --region=$REGION \
          --display-name=$MODEL_NAME \
          --artifact-uri=$MODEL_URI \
          --container-image-uri=us-docker.pkg.dev/vertex-ai/prediction/pytorch-cpu.2-1:latest
          
    # Step 5: Deploy model to Vertex AI Endpoint
    - name: Deploy Model to Endpoint
      run: |
        ENDPOINT_NAME="gitdeployendpoint"
        REGION="us-east1"

        # Check if endpoint exists
        ENDPOINT=$(gcloud ai endpoints list --region $REGION --filter="displayName=$ENDPOINT_NAME" --format="value(name)")

        if [ -z "$ENDPOINT" ]; then
          # Create endpoint if it doesn't exist
          ENDPOINT=$(gcloud ai endpoints create \
            --region $REGION \
            --display-name=$ENDPOINT_NAME \
            --format="value(name)")
        fi

        # Deploy model to endpoint
        gcloud ai endpoints deploy-model \
          --region=$REGION \
          --endpoint=$ENDPOINT \
          --model-display-name="gitdeploy" \
          --traffic-split=0=100 \
          --machine-type="n1-standard-2"

    # Step 6: Get Endpoint URI
    - name: Get Endpoint URI
      run: |
        ENDPOINT=$(gcloud ai endpoints list --region us-east1 --filter="displayName=gitdeploy" --format="value(name)")
        echo "Endpoint URI: https://us-east1-aiplatform.googleapis.com/v1/$ENDPOINT"
