name: Stream
on:
  push:
    branches:
      - dhanush_model
  pull_request:
    branches:
      - dhanush_model
  workflow_dispatch:
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  IMAGE_NAME: "ml-model-image"
  REGISTRY: "us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ml-models-new"
  GCS_BUCKET: "nih-dataset-mlops"

jobs:
  deploy-to-vertex-ai:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3


    #Google Cloud Authentication
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'      

   


     
    # Step 9: Get Endpoint URI
    - name: Get Endpoint URI
      run: |
        GCP_PROJECT_ID='812555529114'
        REGION="us-east1"
        ENDPOINT=$(gcloud ai endpoints list --region us-east1 --filter="displayName='gitmodelendpoint'" --format="value(name)")
        echo "Endpoint URI: https://us-east1-aiplatform.googleapis.com/v1/projects/${GCP_PROJECT_ID}/locations/${REGION}/endpoints/$ENDPOINT_NAME:predict"
      
    # Step 10: Streamlit Application Deployment.
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit torch torchvision pillow requests

    - name: Deploy/Run Streamlit App
      run: |
        streamlit run streamlit_application/deploy_streamlit.py
      env:
        PORT: 8501
