name: Deploy Streamlit to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Authenticate with Google Cloud
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    # Step 3: Set up gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: "${{ secrets.GCP_PROJECT_ID }}"
        install_components: beta

    # Step 4: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy streamlit-app \
          --source . \
          --region us-east1 \
          --allow-unauthenticated
