name: Stream
on:
  push:
    branches:
      - dhanush_model
  pull_request:
    branches:
      - dhanush_model
  workflow_dispatch:
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  IMAGE_NAME: "streamlit-app-image"
  REGISTRY: "us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/streamlit-apps"
  GCS_BUCKET: "nih-dataset-mlops"

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Authenticate with Google Cloud
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    # Step 3: Set up gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: "${{ secrets.GCP_PROJECT_ID }}"
        install_components: beta

    # Step 4: Build and Push Docker Image.
    - name: Build and Push Docker Image
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME:latest .
        docker push $REGISTRY/$IMAGE_NAME:latest

    # Step 5: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy streamlit-app \
          --image $REGISTRY/$IMAGE_NAME:latest \
          --platform managed \
          --region us-east1 \
          --allow-unauthenticated
