# .github/workflows/docker-artifact.yml

name: Build and Push Docker Image to Google Artifact Registry

on:
  push:
    branches: [ dheeraj_model ]
  pull_request:
    branches: [ dheeraj_model ]
  workflow_dispatch:

env:
  GCP_PROJECT_ID: secrets.black-resource-440218-c3  # Your GCP Project ID
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}          # The service account key stored as a secret
  IMAGE_NAME: 'hello-world-image'
  REGISTRY: 'us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ml-models'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Login to GCP Artifact Registry
      - name: Login to GCP Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest .
          docker push $REGISTRY/$IMAGE_NAME:latest

      # Step 5: Run Hello World from Docker Image
      - name: Run Hello World
        run: |
          docker run --rm $REGISTRY/$IMAGE_NAME:latest
